language: node_js
node_js:
- 5.5.0
install:
- npm install
script:
- npm run lint && npm run build-navbar
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: components.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: "$QA_AWS_KEY"
  secret_access_key: "$QA_AWS_SECRET"
  bucket: components.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: release
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: "$PROD_AWS_KEY"
  secret_access_key: "$PROD_AWS_SECRET"
  bucket: components.topcoder.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
env:
  matrix:
  - CXX=g++-4.8
  global:
  # NPM_EMAIL
  - secure: "kmo0afPY5HwJ5SryNY0XRRRekxd1teBR6lSiw2jtjU64sOdpjN7ZhGWy9q0lReGk6hloPfXewXRlpCbcDRFoxvJUdAbQoAN8gq/BxrwGmWlBepgUew1O6WLkpvqXCMe6lUmPEznjil2anjLHfm/cKiqwaY1n8MI+PSna6eNwAlffx72uPL1TzrijJjb7kKqTtjTHZzNiiUn2jZrc35G+MeryZmnd5xXV7cXgYb+flEMC5sDqhcO2aewYiCGMK2b3f7QDJFbGD4+v+HjN1XispJgCxDLTRLJ0HD8HPj87w/7s7PHqCuRUwga1Z2HTRDniqM7mb7TZ5RK990Olp4d1Fw/ApXhUEe4fwgTdN9PSwOzOrY4VGNyytYvJuMVqSVGIHx6Y2BuCt3gzPeM0ev8bjhE9PItYmDTr5FhNI1XLT7PKu+Ktp72bmdEVqNfnv7jXRKba9AeSBQVk70jKMpYAuGI/d/xXeaD2vImBhCflc0UArYfXf+JYMEwzhiMZQfq6csvg0UV/nlD9xidgBLt8QUGdFaQTjsQLt9CWbwcKM7/yFcfkOKEHrM5By1Do4gtSDxmK5F+81210YMO30OVwllHk/f+jOspti9EJv6r0vAZOkKXXL15VsyKQSrF/p6k+brVf0cQcnUMiSiNsl/aEftNW2ys5VCIRJcEol5bHt90="
  # NPM_API_KEY
  - secure: "OoRE9rbEzfAomE1h+PRDHJb0SgcyManma54qs72nwlBA3N4D+hV2Swy0xAidnVqdNvBlA4p9QmcrE0km+ZGVacFEhvleUGFDn5weWde2bukzkkdHtbaYQjyhxbrqfLA9G9vzs1BlHjhrR7Arl2TQuT21XnfagFBQ/LCgCRRu9yHHkZ4TejhuYu/9Fgdq08wnBpLZn7wllUq0OtrDgEgjK7avZ+yv5ob6zccxr3NAAchbdPJ2yUo82VvD+YdQaWbLq9ac5cwa0I6f/RuQUiZcLZItk/H3NuQqg32746QdwIqKpw5dh9wzddbckIK3WVsoJmE+7WpGAOgUU/TxmPijH6j1YwQ9uqcBGsax8RUFR+mG7imlS4YpL67K438JPUG7NCPgnN19zN/c+4WkVoKlLYEncyPp0C3sBbmauR0uuuVBWWUJL/1xBCuPyhT9JGXaocms/Ldshxr+TYf1tfQQ3uzs6wO3cniw3wIgXbgMF6NBwQdQpgUlSh++XJKgIG2I228GI3qMq8zJu/N/1oEKVkKkO8Z9Y3Vd5uo2VMbkp0KJJEfXnE8GZBBaajD+F8jONRQqYEDhK8EMYuqKhsQZMw3RgPtvOZNG+bhcnbElNnMjhd8CTKioKXAslkTP6Esi4Ce2PS6YR4CskjZaO7IT9KRqHvVZN42vlIVbhb2J0RI="
  # AWS_SECRET
  - secure: yFpLFrM42STWqxw6dlVvyr0hvBbVAOHhkKQ1yQcuZ4MtTktCUOItUt9hZTExy659sJJxeBsT0YD66FdVggV+rTG8KDFGcBZJ8RZqN2AHa1+PMZfzF5N35bkacOWoKd1aAReRWZcVspvHjC1h6lAlVR69qSRqRhOL7/IMTDYrZMMwuS7/Pqb0jfdCJgiOf8uFwAn1ZVsJvDvC7AcxYYNLMA+GFD6ay7GX4zoqBdHwcyupKU4g+Fwjy3673kZwfWKITtzmwmV18p0SIiqQp68K6lvsZ2H7Hw6TXOEMkvda1YMD+lmV/dcc6o6W6bsDAk2cZx5JxSu3trvhkpYpK9JE6FUJ1I5ITiPkAZYAnIjckSM+rLZ6Vanxtmc0zNL6cxc4DTfu7V8dQ2MlPxHV125rMspYeJcxi8u/nlSRSJy2C8jaPGzaBQmHM9HlzJNhpTeR4A/3YqTcbcRMgMxvuuslHEUXDeTV+lqfhw1pLvD+Ut+Q6IBkNVdMDVBoeLvuwtXwyFF4skuEcTvOezmh9VNNrMgx2ZcPnJR85aUD+A/MoYihn1dPr66rh2vNJSRKp4uQdgRnldtLaHh5JgX3cR0PPtSat99shV/YkhhGG3WGl6lqOLPQTDX9XLLm9mTmOQzAK7p6GjRKM1PVWOc+3VA8dc3XTCMjBaFh9zgtSsfDibs=
  # AWS_KEY
  - secure: QXxHO6Dt5kGDsN2hjSk//0Rf3eHsjOXBq9CdK1kyePLDks6J1wCUp7hT3PMqZG3wH8yd6i4m8mielDdOurquOHVZgdiWaDRw/FMggRcmOGzCl96Afdz199v4ep6aS1YzndEPmwaKp2jFiCsg8LvByJjlHKtGSWc4Yw7+B1WjSygLoZ1eU4TYeig3xfhHE2ENoIGdnk5DDSjZ2xypqc8upmQIbfFya2dd0nMwA8GjEpVWGAYJy3RhOyKlWKGvO2sW+bf3DVCqnYvLRs8kAGh7qQV//rkkycNWFVUsQZkNd0+mX7bi16aJoaj4HSiW4pR/Z0yDa55Lb7CZKdP0sZgKcojUqkUe8faU8N7LQEkK0RYF7zfSAt2y0ns25Nt7os1xUdY/3Xluw0SMzTR5zX8PiEUVtQyFS33T43GKuQT4joYCseIFCqpZ1a5iYemlR9M7DqZDPQ8TkwHn2yzP59ax25U3FB3AYMz6pd2WuIKsa3XU9irJOiGSHXC3YmS2H70cZpL+r4OxtmsjXVR5RQQWcGEurb3vadk/Iq5S4EXKG9M9HKtLCysGPdynw3/+0GlscdIf+O2eZSvFJfahcVvaPSUxLgyOFM+W3sd0EwjGnTWwXu9zN7LbMr57vqzNUZ0mgSNX7qz2+z9V4jBTNRk5DaG5vRr+7uDHgKdtNQHYWUU=
  # QA_AWS_SECRET
  - secure: "BEjtXJWPIgyOY9oDYZf3sMGmmW4FFOWZEwdWc+nejDkcQxScN5ACTplRKwNUnxu3pvaxdjpp/DPn2N6/fXwpXrF7zpnydEeDJQu83L00JsOPRH67Uq9cbA06OZb1FYsKnQ+p7ssMLMRIgFUC8YDR0VT/qZ0jEZw3knntQof93vs6r3l2c3Zto6bL0BQb4Mm2T7Ui172un3rcImmGRwVfpjGgkmSEUNKobUJS7LKr0xPQfdMQ/UEv9VJEwb/YZdHXhOMeH6hO5ZoYTWEX32HLr3akAhmAj99Jmo71NDTrfrpZWTc4PZZQvKQNDI+JAxsCCqNkMdEN0EuO3ZsKZw0tt4ksRt3UL2yXhhd9PdFmyCnhWrIJ3OQuLtOyrFC1V6tRuE4u1cezvPCpYFuFWMO9nnEyR1jbg63X/bgAbKbl1EV/dUySdHPscToQhr2p0szJYIoR5noW1aGr417yutPKssBtdEQKjbu90efeH2zyDe118nqQ95SkpMtyG9Dmhnfz6YYLtCoLPz7xeTLi1VXz79NbWOMgftK/R8aJ/IHXqyX+F01wp4YjOcgheq3HwLzcWqZ25N497HUkQ07Y54wbs5zh1gTpF8Jua2b+egCCGtlGJT3/W4GEhWGQ8yTcoBYctLuo16mQyDChKeFg8dE8+PS2QRmYTGofrd9pn3W8Y+w="
  # QA_AWS_KEY
  - secure: "DnV3CEYlzTjrAi1bmip2P1ljZ2nZPdTD051+n2SSZapfgmo/pqy3a+fJ1Ct8Lh2x0Nfw+XtyI2mfFV4Vs2LGeHzoPfEYOXtFJZf9L0/mE/RSgR/qLr0OA8324qpJtTdrI1CKq0j5Q6gXKm+RvCVTevJITWdOQmrAD75iqTdezCgvqkz/cYNB6y4/3fezIn1ox0g6W3o3XmM3B1//q5YbP2JW2AVYH83VCMG0wF2codEUKHJchnM9psDgZ/g79D7e378yK6X1tgcol6s9pOp8+8PIZHYjeKV139a/ZIkSPWmnMOFdM6sXinJe1uVrrKHw2oP6PshhAVI+DhH2JGEWoxfezdqMMXZ12x543lPFSHisbHBoyycrZJRpEMVDjto5pUsxTMvWeNGOJveJCv52zxm1+Jy26OC8ssq0WjUGMO0fYwtBL9Ts1iuZSKd6qF5GqdstKYQss771pgsVi2abGuURa1+z311bERV8YDlphyspRw1lS/cI1R40HxSGMD/fZeZhMAotzfrTcRpZgYP7/ViGCte9tmwnH+WK0t2/YxFigtB0J8Aq57EOl5WWXs99tW0Ypk9NbTjNwDxUi4O6g97teR1/D0NmowKE+FLoaibnsy/ic5qUFRSB0RavPSRRpFKRUNcSgGKUuTIvG4BFTXD6SPsSxXs3r1J7Jy2H9o8="
  # PROD_AWS_SECRET
  - secure: "br10xaM6/+62Ge0qPeNUhXSV4agMRB8buARy6tySw3679RyCcAHbLSL5chearYju5hiCMGiBn09yioaxZeHsAWrIflxrlMtB0ZiAWnJjHmE+y0Cq2K+ohwjHiek1jKfFYw/SsDCIfxxqX/fPoS6QTpGe35MtjrbVMWttEW/fP62moIAh2GDp8tF0iHnAMFcAFuTiNbc+TCWF+tbAbU1afSpNpVYrs5nKbnrBOI0PWbK4r56TLpMY7fPwAb+c0vcTnoOtFDGeiPweSDXkUTkW/wlA68Ayqj7yg7lRErzi1UpEBroajFaTmYfoX6VdZo1EIzmOmxykcdfKwI/x+mqO1PnwAZNxhu3zR6uhEk0b1AkR5K/DZU/SH5FTxWOI8PsmssuPj/3e4ovTAFAL2e+LSJdQnHOF+epBH83mAnjbjahS72EZC4i9s4+9w1WVACLFL4Fadm5VnP11A+YPbafoPDqIXOtF5hXkMmrO8cw0VeSZWXfBDZ+YjAgF7CP4bV9X7ZqVYbOipcqv1Ml5FXne/jJn6j+tQMoBKZh7W1AF/ue/ixRhQCn4MTQ+n5OFow+x0/FRHI+D1WAUbVTNDviBYY7e682oATGCdra0uE2PeREKuh9OR/ZqH0CARHkAVAZWu2UrkdR+HlEhVmBwnp2Nw6EQBR8v9jezAUjucue9GjA="
  # PROD_AWS_KEY
  - secure: "tPQLujveVEb1rhHHaecio/30gISQ2PHODfyeN27BfCY/1nBTif50n7+HbWC9YClyMqqN1odlV5bGuRBYNaz/F6gRxHXta1MGvP/VmrFtrEY69BhxXE23py6w4kVvNelEO8bw7u4JITM73nkGtQMfJumQhJ0lBVYI4I0CeQBVgd9WoUNRmHfcosOQkxIpFerg8sWGfOqHqIxZ/9UnH5e7zHIdFNGGAeFKqYhnFirWiSEkHunSBbknZv/+8CcGsULSKbM2TngpaDMjc0k6fKj/EtLopOyTHraO0VxoKk50irqSaUSIigzgyalj7zK94mR2+vQtRVYrvd//lbDZwhuX3zV/nJvkmy5poVoSBFwtq/StpsaII9hbA4CppMg+A4OGdpLdWwWVfcXYOSpVAqydjxR46Bi8pcgBTRkJlNWmoPDIa9niy8/iTKJiTrPmJ+uj9NOc2pCAghj2QB9z8Wrk6c6P8BVHT6T3agYB+5MZhLXjPUOPsPt6Y1l7M5v0NGTcYlMNYQMmHnUdQ7+xc02hQ0BUhddWnVm7CESTOYe865HNine853TGYO2megU7b25yEXKddJKV5P6odrGBVhazLpztev2YrWFhS9Iv9VInGvDCtvaq/pF00UVptH4gsb4VQr3KNOe5jw7hUCRuy4PGUgLTejolD1sQ7gbr1dtCH08="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
